analytics_dashboard/analytics_dashboard/urls.py
# pylint: disable=line-too-long,no-value-for-parameter
import os

from django.conf.urls import patterns, include, url
from django.conf import settings
from django.contrib import admin
from django.core.urlresolvers import reverse_lazy
from django.views.generic import RedirectView

from analytics_dashboard import views


admin.autodiscover()

js_info_dict = {
    'packages': ('analytics_dashboard', 'courses',),
}

urlpatterns = patterns(
    '',
    url(r'^$', views.LandingView.as_view(), name='landing'),
    url(r'^jsi18n/$', 'django.views.i18n.javascript_catalog', js_info_dict),
    url(r'^status/$', views.status, name='status'),
    url(r'^health/$', views.health, name='health'),
    url(r'^courses/', include('courses.urls', namespace='courses')),
    url(r'^admin/', include(admin.site.urls)),
    url('', include('social.apps.django_app.urls', namespace='social')),
    url(r'^accounts/login/$',
        RedirectView.as_view(url=reverse_lazy('social:begin', args=['edx-oidc']), permanent=False, query_string=True),
        name='login'),
    url(r'^accounts/logout/$', views.logout, name='logout'),
    url(r'^accounts/logout_then_login/$', views.logout_then_login, name='logout_then_login'),
    url(r'^test/auto_auth/$', views.AutoAuth.as_view(), name='auto_auth'),
    url(r'^auth/error/$', 'django.views.defaults.server_error', {'template_name': 'auth_error.html'},
        name='auth_error'),
    url(r'^announcements/', include('announcements.urls')),
)

if settings.DEBUG:  # pragma: no cover
    urlpatterns += patterns(
        '',
        url(r'^403/$', 'django.views.defaults.permission_denied'),
        url(r'^404/$', 'django.views.defaults.page_not_found'),
        url(r'^500/$', 'django.views.defaults.server_error'),
    )

    if os.environ.get('ENABLE_DJANGO_TOOLBAR', False):
        import debug_toolbar  # pylint: disable=import-error

        urlpatterns += patterns(
            '',
            url(r'^__debug__/', include(debug_toolbar.urls)),
        )

analytics_dashboard/courses/urls.py
# pylint: disable=no-value-for-parameter

from django.conf.urls import url, patterns, include

from courses import views

COURSE_ID_PATTERN = r'(?P<course_id>[^/+]+[/+][^/+]+[/+][^/]+)'

COURSE_URLS = patterns(
    '',
    # Course homepage. This should be the entry point for other applications linking to the course.
    url(r'^$', views.CourseHome.as_view(), name='home'),
    url(r'^enrollment/activity/$', views.EnrollmentActivityView.as_view(), name='enrollment_activity'),
    url(r'^enrollment/geography/$', views.EnrollmentGeographyView.as_view(), name='enrollment_geography'),
    url(r'^enrollment/demographics/age/$', views.EnrollmentDemographicsAgeView.as_view(),
        name='enrollment_demographics_age'),
    url(r'^enrollment/demographics/education/$', views.EnrollmentDemographicsEducationView.as_view(),
        name='enrollment_demographics_education'),
    url(r'^enrollment/demographics/gender/$', views.EnrollmentDemographicsGenderView.as_view(),
        name='enrollment_demographics_gender'),
    url(r'^engagement/content/$', views.EngagementContentView.as_view(), name='engagement_content'),
    url(r'^csv/enrollment/$', views.CourseEnrollmentCSV.as_view(), name='csv_enrollment'),
    url(r'^csv/enrollment_by_country/$', views.CourseEnrollmentByCountryCSV.as_view(),
        name='csv_enrollment_by_country'),
    url(r'^csv/enrollment_demographics_age/$', views.CourseEnrollmentDemographicsAgeCSV.as_view(),
        name='csv_enrollment_demographics_age'),
    url(r'^csv/enrollment_demographics_education/$', views.CourseEnrollmentDemographicsEducationCSV.as_view(),
        name='csv_enrollment_demographics_education'),
    url(r'^csv/enrollment_demographics_gender/$', views.CourseEnrollmentDemographicsGenderCSV.as_view(),
        name='csv_enrollment_demographics_gender'),
    url(r'^csv/engagement_activity_trend/$', views.CourseEngagementActivityTrendCSV.as_view(),
        name='csv_engagement_activity_trend')
)

urlpatterns = patterns(
    '',
    url('^$', views.CourseIndex.as_view(), name='index'),
    url(r'^{}/'.format(COURSE_ID_PATTERN), include(COURSE_URLS))
)

analytics_dashboard/courses/views.py
import copy
import datetime
import json
import logging
import re
import urllib

from django.contrib.humanize.templatetags.humanize import intcomma
from django.core.cache import cache
from django.utils.functional import cached_property
import edx_api_client
import requests
from django.conf import settings
from django.core.exceptions import PermissionDenied
from django.core.urlresolvers import reverse
from django.http import Http404, HttpResponse
from django.utils import dateformat
from django.views.generic import TemplateView
from django.utils.translation import ugettext_lazy as _
from braces.views import LoginRequiredMixin
from slumber.exceptions import HttpClientError
from waffle import switch_is_active
from analyticsclient.constants import data_format, demographic
from analyticsclient.client import Client
from analyticsclient.exceptions import NotFoundError

from courses import permissions
from courses.presenters import CourseEngagementPresenter, CourseEnrollmentPresenter, \
    CourseEnrollmentDemographicsPresenter
from courses.serializers import LazyEncoder
from courses.utils import is_feature_enabled
from help.views import ContextSensitiveHelpMixin


logger = logging.getLogger(__name__)


class CourseAPIMixin(object):
    course_api_enabled = False
    course_api = None
    course_id = None

    @cached_property
    def course_info(self):
        """
        Returns course info.

        All requests for course info should be made against this property to take advantage of caching.
        """
        return self.get_course_info(self.course_id)

    def dispatch(self, request, *args, **kwargs):
        self.course_api_enabled = switch_is_active('enable_course_api')

        if self.course_api_enabled:
            self.course_api = edx_api_client.Client(settings.COURSE_API_URL, settings.COURSE_API_KEY).courses

        return super(CourseAPIMixin, self).dispatch(request, *args, **kwargs)

    def get_course_info(self, course_id, depth=0, extra_fields=None):
        """
        Retrieve course info from the Course API.

        Retrieved data is cached.

        Arguments
            course_id       -- ID of the course for which data should be retrieved
            depth           -- Number of (tree) levels worth of data to retrieve
            extra_fields    -- Additional course fields to retrieve
        """
        if extra_fields:
            extra_fields = u','.join(extra_fields)
        else:
            extra_fields = u''

        key = u'_'.join([unicode(course_id), unicode(depth), extra_fields])
        info = cache.get(key)

        if not info:
            try:
                extra_fields = extra_fields or ''
                info = self.course_api(course_id).get(depth=depth, include_fields=extra_fields)
                cache.set(key, info)
            except HttpClientError as e:
                logger.error("Unable to retrieve course info for {}: {}".format(course_id, e))
                info = {}

        return info

    def get_courses(self, course_ids=None):
        if course_ids:
            ','.join(course_ids)

        try:
            return self.course_api.get(course_id=course_ids)['results']
        except HttpClientError as e:
            logger.error("Unable to retrieve course data: {}".format(e))
            return []


class TrackedViewMixin(object):
    """
    Adds tracking variables to the context passed to Javascript.
    """

    # Page name used for usage tracking/analytics
    page_name = None

    def get_context_data(self, **kwargs):
        context = super(TrackedViewMixin, self).get_context_data(**kwargs)
        context['js_data'] = context.get('js_data', {})
        context['js_data'].update({
            'tracking': {
                'segmentApplicationId': settings.SEGMENT_IO_KEY,  # None will translate to 'null'
                'page': self.page_name
            }
        })
        return context


class LazyEncoderMixin(object):
    def get_page_data(self, context):
        """ Returns JSON serialized data with lazy translations converted. """
        if 'js_data' in context:
            return json.dumps(context['js_data'], cls=LazyEncoder)
        else:
            return None


class CourseContextMixin(CourseAPIMixin, TrackedViewMixin, LazyEncoderMixin):
    """
    Adds default course context data.

    Use primarily with templated views where data needs to be passed to Javascript.
    """
    # Title displayed on the page
    page_title = None
    page_subtitle = None

    def _ignore_in_reporting(self, user):
        if settings.SEGMENT_IGNORE_EMAIL_REGEX:
            return bool(re.match(settings.SEGMENT_IGNORE_EMAIL_REGEX, user.email))

        return False

    def get_context_data(self, **kwargs):
        context = super(CourseContextMixin, self).get_context_data(**kwargs)
        context.update(self.get_default_data())

        user = self.request.user
        context['js_data'] = context.get('js_data', {})
        context['js_data'].update({
            'course': {
                'courseId': self.course_id
            },
            'user': {
                'username': user.get_username(),
                'name': user.get_full_name(),
                'email': user.email,
                'ignoreInReporting': self._ignore_in_reporting(user)
            },
        })

        return context

    def get_default_data(self):
        """
        Returns default data for the pages (context and javascript data).
        """
        context = {
            'course_id': self.course_id,
            'course_key': self.course_key,
            'page_title': self.page_title,
            'page_subtitle': self.page_subtitle,
        }

        if self.course_api_enabled:
            context['course_name'] = self.course_info.get('name')

        return context


class CourseValidMixin(object):
    """
    Mixin that checks the validity of a course ID against the LMS.
    """

    course_id = None

    def is_valid_course(self):

        if settings.LMS_COURSE_VALIDATION_BASE_URL:
            uri = '{0}/{1}/info'.format(settings.LMS_COURSE_VALIDATION_BASE_URL, self.course_id)

            try:
                response = requests.get(uri, timeout=5)
            except requests.exceptions.Timeout:
                logger.error('Course validation timed out: {}'.format(uri))
                # consider the course valid if the LMS times out
                return True

            # pylint: disable=no-member
            return response.status_code == requests.codes.ok
        else:
            # all courses valid if LMS url isn't specified
            return True

    def dispatch(self, request, *args, **kwargs):
        if self.is_valid_course():
            return super(CourseValidMixin, self).dispatch(request, *args, **kwargs)
        else:
            raise Http404


class CoursePermissionMixin(object):
    course_id = None
    user = None

    def can_view(self):
        return permissions.user_can_view_course(self.user, self.course_id)

    def dispatch(self, request, *args, **kwargs):
        if settings.ENABLE_COURSE_PERMISSIONS and not self.can_view():
            raise PermissionDenied

        return super(CoursePermissionMixin, self).dispatch(request, *args, **kwargs)


class CourseNavBarMixin(object):
    """
    Mixin to add navbar items to context.

    This mixin is intended for course views that have a course_id property.
    """

    # Primary nav item that should be displayed as active. This value MUST be overwritten by the child class.
    active_primary_nav_item = None

    # Secondary nav item that should be displayed as active. This value is optional.
    active_secondary_nav_item = None

    # Tertiary nav item that should be displayed as active. This value is optional.
    active_tertiary_nav_item = None

    # Items that will populate the secondary nav list. This value is optional.
    secondary_nav_items = []

    # Items that will populate the tertiary nav list. This value is optional.
    tertiary_nav_items = []

    def get_primary_nav_items(self):
        """
        Return the primary nav items.
        """

        items = [
            {
                'name': 'enrollment',
                'label': _('Enrollment'),
                'view': 'courses:enrollment_activity',
                'icon': 'fa-child'
            },
            {
                'name': 'engagement',
                'label': _('Engagement'),
                'view': 'courses:engagement_content',
                'icon': 'fa-bar-chart',
            }
        ]

        # Remove disabled items
        items = filter(is_feature_enabled, items)

        # Clean each item
        map(self.clean_item, items)

        return items

    def _build_nav_items(self, nav_items, active_item):
        # Deep copy the list since it is a list of dictionaries
        items = copy.deepcopy(nav_items)

        # Process only the nav items that are enabled
        items = filter(is_feature_enabled, items)

        for item in items:
            item['active'] = active_item == item['name']
            self.clean_item(item)

        return items

    def get_secondary_nav_items(self):
        """
        Return the secondary nav items.
        """
        return self._build_nav_items(self.secondary_nav_items, self.active_secondary_nav_item)

    def get_tertiary_nav_items(self):
        """
        Return the tertiary nav items.
        """
        return self._build_nav_items(self.tertiary_nav_items, self.active_tertiary_nav_item)

    def clean_item(self, item):
        """
        Remove extraneous keys from item and set the href value.
        """
        # Prevent page reload if user clicks on the active navbar item, otherwise navigate to the new page.
        if item.get('active', False):
            href = '#'
        else:
            href = reverse(item['view'], kwargs={'course_id': self.course_id})

        item['href'] = href

        # Delete entries that are no longer needed

analytics_dashboard/courses/templates/courses/engagement_content.html
{% extends "courses/base-course.html" %}

{% load i18n %}
{% load staticfiles %}
{% load waffle_tags %}
{% load dashboard_extras %}
{% load rjs %}

{% comment %}
Individual course-centric engagement content view.
{% endcomment %}

{% block view-name %}view-course-engagement view-dashboard{% endblock view-name %}

{% block javascript %}
  {{ block.super }}
  <script src="{% static_rjs 'js/engagement-content-main.js' %}"></script>
{% endblock javascript %}

{% block child_content %}
  <section class="view-section" aria-hidden="true">
    <div class="section-heading">
      <h4 class="section-title">{% trans "Weekly Student Engagement" %}</h4>
      <span class="section-heading-note small">{% trans "How many students are interacting with my course?" %}</span>
    </div>

    {% if js_data.course.engagementTrends %}
        <div class="section-content section-data-graph">
          <div class="section-content section-data-viz">
                <div class="analytics-chart-container">
                    <div class="chart-info">{% trans "Students" %}</div>
                    {% trans "The number of active students, and the number of students who engaged in specific activities, over time." as tip_text %}
                    {% include "chart_tooltip.html" with tip_text=tip_text track_category="trend"%}
                    <div id="engagement-trend-view" class="analytics-chart">
                        {% include "loading.html" %}
                    </div>
                </div>
          </div>
        </div>
    {% else %}
        {% show_chart_error %}
    {% endif %}
  </section>

  <section class="view-section">
    <div class="section-heading bordered">
      <h4 class="section-title">{% trans "Student Activity Metrics" %}</h4>
    </div>

    {% if summary %}
        <div class="row">
          <div class="col-xs-12 col-sm-3" data-activity-type="any">
            {% trans "Active Students Last Week" as label %}
            {% trans "Students who visited at least one page in the course content." as tooltip %}
            {% summary_point summary.any label tooltip=tooltip %}
          </div>

          <div class="col-xs-12 col-sm-3" data-activity-type="played_video">
            {# Translators: This is a label indicating the number of students who watched a video. #}
            {% trans "Watched a Video Last Week" as label %}
            {% trans "Students who played one or more videos." as tooltip %}
            {% summary_point summary.played_video label tooltip=tooltip %}
          </div>

          <div class="col-xs-12 col-sm-3" data-activity-type="attempted_problem">
            {# Translators: This is a label indicating the number of students who tried a problem. #}
            {% trans "Tried a Problem Last Week" as label %}
            {% trans "Students who submitted an answer for a standard problem. Not all problem types are included." as tooltip %}
            {% summary_point summary.attempted_problem label tooltip=tooltip %}
          </div>

          {% switch show_engagement_forum_activity %}
            <div class="col-xs-12 col-sm-3" data-activity-type="posted_forum">
              {# Translators: This is a label indicating the number of students who posted in a forum discussion. #}
              {% trans "Posted in a Discussion Last Week" as label %}
              {% trans "Students who contributed to any discussion topic." as tooltip %}
              {% summary_point summary.posted_forum label tooltip=tooltip %}
            </div>
          {% endswitch %}
        </div>
    {% else %}
        {% show_metrics_error %}
    {% endif %}
  </section>

  <section class="view-section">
    <div class="section-heading">
      <h4 class="section-title">{% trans "Content Engagement Breakdown" %}</h4>

      <div class="section-actions">
        {% if js_data.course.engagementTrends %}
            <a href="{% url 'courses:csv_engagement_activity_trend' course_id=course_id %}" class="btn btn-default"
               data-role="engagement-trend-csv" data-track-type="click"
               data-track-event="edx.bi.csv.downloaded" data-track-category="trend">
              <i class="ico fa fa-download" aria-hidden="true"></i> {% trans "Download CSV" %}
              <span class="sr-only">{% trans "Content Engagement Breakdown" %}</span>
            </a>
        {% endif %}
      </div>
    </div>

    {% if js_data.course.engagementTrends %}
        <div class="section-content section-data-table" data-role="engagement-table">
          {% include "loading.html" %}
        </div>
    {% else %}
        {% show_table_error %}
    {% endif %}
  </section>
{% endblock %}

analytics_dashboard/courses/templates/courses/enrollment_activity.html
{% extends "courses/base-course.html" %}
{% load i18n %}
{% load dashboard_extras %}
{% load staticfiles %}
{% load rjs %}
{% load waffle_tags %}

{% comment %}
Individual course-centric enrollment activity view.
{% endcomment %}

{% block view-name %}view-course-enrollment view-dashboard{% endblock view-name %}

{% block javascript %}
  {{ block.super }}
  <script src="{% static_rjs 'js/enrollment-activity-main.js' %}"></script>
{% endblock javascript %}


{% block child_content %}

  <section class="view-section" data-section="enrollment-basics" aria-hidden="true">
    <div class="section-heading">
      <h4 class="section-title">{% trans "Daily Student Enrollment" %}</h4>
      <span class="section-heading-note small">{% trans "How many students are in my course?" %}</span>
    </div>

    {% if js_data.course.enrollmentTrends %}
      <div class="section-content section-data-graph">
        <div class="section-content section-data-viz">
          <div class="analytics-chart-container">
            <div class="chart-info">{% trans "Enrollments" %}</div>
            {% trans "This graph displays total enrollment for the course calculated at the end of each day. Total enrollment includes new enrollments as well as unenrollments." as tip_text %}
            {% include "chart_tooltip.html" with tip_text=tip_text track_category="trend" %}
            <div id="enrollment-trend-view" class="analytics-chart">
              {% include "loading.html" %}
            </div>
          </div>
        </div>
      </div>
    {% else %}
      {% show_chart_error %}
    {% endif %}
  </section>

  <section class="view-section">
    <div class="section-heading bordered">
      <h4 class="section-title">{% trans "Enrollment Metrics" %}</h4>
    </div>

    {% if summary %}
      <div class="section-content">
        <div class="row">
          <div class="col-xs-12 col-sm-3" data-stat-type="current_enrollment">
            {# Translators: This is a label to identify current student enrollment. #}
            {% trans "Total Enrollment" as label %}
            {# Translators: This is a label indicating the number of students enrolled in a course. #}
            {% trans "Students enrolled in the course." as tooltip %}
            {% summary_point summary.current_enrollment label tooltip=tooltip %}
          </div>

          <div class="col-xs-12 col-sm-3" data-stat-type="enrollment_change_last_7_days">
            {# Translators: This is a label indicating the change in the number of students enrolled in a course since the previous week. #}
            {% trans "Change in Last Week" as label %}
            {% trans "The difference between the number of students enrolled at the end of the day yesterday and one week before." as tooltip %}
            {% summary_point summary.enrollment_change_last_7_days label tooltip=tooltip %}
          </div>

          {% switch display_verified_enrollment %}
            {% if not summary.verified_enrollment == None %}
              <div class="col-xs-12 col-sm-3" data-stat-type="verified_enrollment">
                {# Translators: This is a label to identify enrollment of students on the verified track. #}
                {% trans "Verified Enrollment" as label %}
                {# Translators: This is a label indicating the number of students enrolled in a course on the verified track. #}
                {% trans "Number of enrolled students who are pursuing a verified certificate of achievement." as tooltip %}
                {% summary_point summary.verified_enrollment label tooltip=tooltip %}
              </div>
            {% endif %}

            {% if not summary.verified_change_last_7_days == None %}
              <div class="col-xs-12 col-sm-3" data-stat-type="verified_change_last_7_days">
                {# Translators: This is a label indicating the change in the number of students enrolled in the verified track of a course since the previous week. #}
                {% trans "Change in Verified Enrollments Last Week" as label %}
                {% trans "The difference between the number of students pursuing verified certificates at the end of the day yesterday and one week before." as tooltip %}
                {% summary_point summary.verified_change_last_7_days label tooltip=tooltip %}
              </div>
            {% endif %}
          {% endswitch %}
        </div>
      </div>
    {% else %}
      {% show_metrics_error %}
    {% endif %}
  </section>

  <section class="view-section">
    <div class="section-heading">
      <h4 class="section-title">{% trans "Enrollment Over Time" %}</h4>

      <div class="section-actions">
        {% if js_data.course.enrollmentTrends %}
          <a href="{% url 'courses:csv_enrollment' course_id=course_id %}" class="btn btn-default"
             data-role="enrollment-trend-csv" data-track-type="click"
             data-track-event="edx.bi.csv.downloaded" data-track-category="trend">
            <i class="ico fa fa-download" aria-hidden="true"></i> {% trans "Download CSV" %}
            <span class="sr-only">{% trans "Enrollment Over Time" %}</span>
          </a>
        {% endif %}
      </div>
    </div>

    {% if js_data.course.enrollmentTrends %}
      <div class="section-content section-data-table" data-role="enrollment-table">
        {% include "loading.html" %}
      </div>
    {% else %}
      {% show_table_error %}
    {% endif %}

  </section>

{% endblock %}

analytics_dashboard/courses/templates/courses/enrollment_demographics_age.html
{% extends "courses/base-course.html" %}
{% load i18n %}
{% load dashboard_extras %}
{% load staticfiles %}
{% load rjs %}

{% block view-name %}view-course-enrollment view-dashboard{% endblock view-name %}

{% block javascript %}
{{ block.super }}
<script src="{% static_rjs 'js/enrollment-demographics-age-main.js' %}"></script>
{% endblock javascript %}


{% block child_content %}

<section class="view-section" data-section="enrollment-basics" aria-hidden="true">
    <div class="row">
        <div class="col-xs-12">
            <div class="tertiary-nav">
                <ul class="nav navbar-nav">
                    {% include "submenu_navigation.html" with nav_items=tertiary_nav_items%}
                </ul>
                <div class="section-heading">
                    <span class="section-heading-note small">{% trans "How old are my students?" %}</span>
                </div>
            </div>
        </div>
    </div>

    {% if js_data.course.ages %}
        <div class="section-content section-data-graph">
            <div class="section-content section-data-viz">
                <div class="analytics-chart-container">
                    {% include "courses/demographics_chart_info.html"%}
                    {% captureas tip_text %}
                      {# Translators: Maintain the double percentage symbols (%%) but move them to the appropriate location (before/after the value placeholder) for your language. #}
                      {% blocktrans with value=chart_tooltip_value %}This age histogram presents data computed for the {{ value }}% of enrolled students who provided a year of birth.{% endblocktrans %}
                    {% endcaptureas %}
                    {% include "chart_tooltip.html" with tip_text=tip_text track_category="histogram"%}
                    <div id="enrollment-chart-view" class="analytics-chart">
                        {% include "loading.html" %}
                    </div>
                </div>
            </div>
        </div>
    {% else %}
        {% show_chart_error %}
    {% endif %}
</section>

<section class="view-section">
    <div class="section-heading bordered">
        <h4 class="section-title">{% trans "Age Metrics" %}</h4>
    </div>

    {% if summary %}
        <div class="section-content">
            <div class="row">

                <div class="col-xs-12 col-sm-3" data-stat-type="median_age">
                    {# Translators: This is a label to identify the median age of enrolled students. #}
                    {% trans "Median Student Age" as label %}
                    {% trans "The midpoint of the student ages, computed from the provided year of birth." as tooltip %}
                    {% summary_point summary.median label tooltip=tooltip %}
                </div>

                <div class="col-xs-12 col-sm-3" data-stat-type="enrollment_age_under_25">
                    {# Translators: This is a label to identify the number of students in the age range. #}
                    {% trans "Students 25 and Under" as label %}
                    {% trans "The percentage of students aged 25 years or younger (of those who provided a year of birth)." as tooltip %}
                    {% summary_point summary.under_25|metric_percentage label tooltip=tooltip %}
                </div>

                <div class="col-xs-12 col-sm-3" data-stat-type="enrollment_age_between_26_40">
                    {# Translators: This is a label to identify the number of students in the age range. #}
                    {% trans "Students 26 to 40" as label %}
                    {% trans "The percentage of students aged from 26 to 40 years (of those who provided a year of birth)." as tooltip %}
                    {% summary_point summary.between_26_40|metric_percentage label tooltip=tooltip %}
                </div>

                <div class="col-xs-12 col-sm-3" data-stat-type="enrollment_age_over_40">
                    {# Translators: This is a label to identify the number of students in the age range. #}
                    {% trans "Students 41 and Over" as label %}
                    {% trans "The percentage of students aged 41 years or older (of those who provided a year of birth)." as tooltip %}
                    {% summary_point summary.over_40|metric_percentage label tooltip=tooltip %}
                </div>


            </div>
        </div>
    {% else %}
        {% show_metrics_error %}
    {% endif %}
</section>

<section class="view-section">
    <div class="section-heading">
        <h4 class="section-title">{% trans "Age Breakdown" %}</h4>
        <div class="section-actions">
            {% if js_data.course.ages %}
                <a href="{% url 'courses:csv_enrollment_demographics_age' course_id=course_id %}"
                   class="btn btn-default"
                   data-role="enrollment-csv" data-track-type="click"
                   data-track-event="edx.bi.csv.downloaded"
                   data-track-category="age">
                    <i class="ico fa fa-download" aria-hidden="true"></i> {% trans "Download CSV" %}
                    <span class="sr-only">{% trans "Enrollment Over Time" %}</span>
                </a>
            {% endif %}
        </div>
    </div>

    {% if js_data.course.ages %}
        <div class="section-content section-data-table" data-role="enrollment-table">
            {% include "loading.html" %}
        </div>
    {% else %}
        {% show_table_error %}
    {% endif %}

</section>

{% endblock %}

analytics_dashboard/courses/templates/courses/index.html
{% extends "base_dashboard.html" %}
{% load i18n %}
{% load staticfiles %}
{% load dashboard_extras %}
{% load firstof from future %}

{% block view-name %}view-course-list{% endblock view-name %}

{% block title %}{% trans "Courses" %} {{ block.super }}{% endblock title %}

{% block header-text %}
  <h3>
    {% blocktrans with username=request.user.username %}Welcome, {{ username }}!{% endblocktrans %}
  </h3>
{% endblock %}

{% block intro-text %}
  {% blocktrans %}Here are the courses you currently have access to in Insights:{% endblocktrans %}
{% endblock intro-text %}

{% block content %}
  <div class="row">
    <div class="col-md-8">
      <div class="course-list">
        {% for course in courses %}
          <div class="course">
            <a href="{% url 'courses:home' course_id=course.key %}">
              <span class="course-name">{% firstof course.name course.key|format_course_key %}</span>
            </a>

            {% if course.name %}
              <div class="course-key">{{ course.key|format_course_key:" / " }}</div>
            {% endif %}
          </div>
        {% endfor %}
      </div>
    </div>

    <div class="col-md-4">
      <div class="help-msg">
        <h4>{% blocktrans %}New to {{ application_name }}?{% endblocktrans %}</h4>

        {% captureas email_link %}
          <a class="feedback-email" href="mailto:{{ feedback_email }}?Subject=Feedback">
            {{ feedback_email }}</a>{% endcaptureas %}

        <p class="info-text">{% blocktrans trimmed %} Click Help in the upper-right corner to get more information
          about {{ application_name }}. Send us feedback at {{ email_link }}.{% endblocktrans %}</p>
      </div>
    </div>
  </div>
{% endblock %}